### ISSUE TITLE
Feiertage sind drei Tage lang

### ISSUE THREAD

**Issue by goekce** [ics-tools/Feiertage#1]
https://feiertage.ics.tools/bayern.ics habe ich im Thunderbird eingebunden. Die Feiertage sind immer drei Tage lang.

Vielen Dank für das Kalenderabo :)

**Comment by Skillkiller** [comment]
Hey,
Ich kann den Fehler soweit bestätigen. Ich werde mich dem Problem die nächsten Tage annehmen. Da muss ich irgendwo bei der Erstellung falsch abgebogen sein.

**Comment by Skillkiller** [comment]
Fixed with https://github.com/ics-tools/ics.tools/pull/3. Sorry for the long waiting time.
